

import SwiftUI
import PlaygroundSupport

public struct OperatorsView2: View {
    
    public init(){}
    
    public var body: some View {
        
            HStack {
                Text("Comparison Operator")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.orange)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" Equal to ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.blue)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" == ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.purple)
                Text(" -> ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text("a = a == b")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.pink)
            }.padding(.vertical, 10)
            
            HStack {
                Text("Comparison Operator")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.orange)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" Not equal to ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.blue)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" != ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.purple)
                Text(" - >")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text("a = a != b")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.pink)
            }.padding(.vertical, 10)
            
            HStack {
                Text("Comparison Operator")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.orange)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" Greater than ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.blue)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" > ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.purple)
                Text(" ->")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text("a = a > b")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.pink)
            }.padding(.vertical, 10)
            
            HStack {
                Text("Comparison Operator")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.orange)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" Less than ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.blue)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" < ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.purple)
                Text(" ->")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text("a = a < b")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.pink)
            }.padding(.vertical, 10)
            
            HStack {
                Text("Comparison Operator")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.orange)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" Greater than or equal to  ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.blue)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" >= ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.purple)
                Text(" ->")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text("a = a >= b")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.pink)
            }.padding(.vertical, 10)
            
            HStack {
                Text("Comparison Operator")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.orange)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" Less than or equal to  ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.blue)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" <= ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.purple)
                Text(" ->")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text("a = a <= b")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.pink)
            }.padding(.vertical, 10)
            
        
        
    }
    
}
