
import SwiftUI
import PlaygroundSupport

public struct OperatorsView1: View {
    
    public init(){}
    
    public var body: some View {
            HStack {
                Text("Assignment Operator")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.orange)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" = ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.purple)
                Text(" -> ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" a = b ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.pink)
            }.padding(.vertical, 10)
            
            HStack {
                Text("Arithmetic Operator")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.orange)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" Addition ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.blue)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" + ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.purple)
                Text(" -> ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text("a = a + b")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.pink)
            }.padding(.vertical, 10)
            
            HStack {
                Text("Arithmetic Operator")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.orange)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" Subtraction ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.blue)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.purple)
                Text(" -> ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text("a = a - b")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.pink)
            }.padding(.vertical, 10)
            
            HStack {
                Text("Arithmetic Operator")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.orange)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" Multiplication ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.blue)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" * ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.purple)
                Text(" -> ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text("a = a * b")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.pink)
            }.padding(.vertical, 10)
            
            HStack {
                Text("Arithmetic Operator")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.orange)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" Division ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.blue)
                Text(" - ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text(" / ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.purple)
                Text(" -> ")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.white)
                Text("a = a / b")
                    .font(.custom("American Typewriter", size: 20))
                    .foregroundColor(Color.pink)
            }.padding(.vertical, 10)
            
    }
    
}
